name: HTML Export

on:
 workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Print context variables
      run: |
        echo "Repository Name:  ${{ github.repository }}"
        echo "Branch Name: ${{ github.ref_name }}"
        echo "Current path: $(pwd)"
#        set
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Checkout called repo
#      if:   ${{ inputs.repo_name != 'Vla100Pers/repo2'}}
      uses: actions/checkout@v4
      with:
        repository:  Vla100Pers/repo3
#        token: ${{ secrets.SEC1 }}
        path: repo3
        ref: main
    - name: Called repo files
      run: |
         ls ${{ github.workspace }}
         ls Vla100Pers/repo3
