name: called wf2

on:
 workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Print context variables
      run: |
        echo "Repository Name:  ${{ github.repository }}"
        echo "Branch Name: ${{ github.ref_name }}"
        echo "Current path: $(pwd)"
        set
    - name: List files in the repository
      run: |
        ls -lah ${{ github.workspace }}
    - name: Checkout called repo
#      if:   ${{ inputs.repo_name != 'Vla100Pers/repo2'}}
      uses: actions/checkout@v4
      with:
        repository: 'Vla100Pers/repo3'
#        token: ${{ secrets.SEC1 }}
        path: repo3
        ref: main

    - name: Copy test_repo1 folder from repo1 to repo3
      run: |
        cp -r test_repo1 repo3/
        
    - name: Called repo files
      run: |
        echo "Listing files in repo3:"
        ls -lah repo3
        
    - name: Commit and Push Changes to repo3
      run: |
        cd repo3
        git config user.name "Vla100Pers"
        git config user.email "vlastimil.polacek@gmail.com"
        git add .
        git commit -m "Copy test_repo1 from repo1 to repo3"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.SEC1 }} # Use the PAT for push
